language: node_js
node_js:
  - 14
before_install: npm i -g npm@latest
script:
  - make
  # - npm run lint
  - npm test
deploy:
  - provider: npm
    skip_cleanup: true
    email: stephan@emliri.com
    tag: latest
    on:
      repo: emliri/multimedia-js
      tags: true
    api_key: $NPM_API_KEY
