language: node_js
node_js:
  - 11
script:
  # - npm run lint
  - make
  - npm test
deploy:
  - provider: npm
    skip_cleanup: true
    email: stephan@emliri.com
    tag: latest
    on:
      repo: emliri/multimedia-js
      tags: true
    api_key: $NPM_API_KEY
